<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help() .
 */
function example_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.example_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' .t('Module who create users and export them') . '</p>';
      return $output;
    default:
  }
}

